7-post-comments
LexieLei98/be-nc-games pull request #5
Opened 2022-12-14 11:47 UTC by LexieLei98

2022-12-14 12:00 UTC, lewispricey requested changes
Awesome work Lexie! Please remove your promise.all from this function and add in the extra test for if a user passes in an additional property.

If you could re-raise a PR for this once done that would be great 😄

2022-12-14 12:00 UTC, lewispricey commented on controllers/controller.games.js
> +        res.status(201).send({comments})
Good choice of naming, It's small but I'd slightly change this to comment as were only sending back a single comment

2022-12-14 12:00 UTC, lewispricey commented on __tests__/app.test.js
> +describe('7. POST /api/reviews/:review_id/comments', () => {
Great testing overall, it would be good to add in a test to make sure if the user passes in a votes or id property that this is ignored and returned as 0

2022-12-14 12:00 UTC, lewispricey commented on controllers/controller.games.js
> +    Promise.all(promises)
I like you're thinking here however if we try and add a comment to an ID that doesn't exist PSQL should thow an error so we don't need to make the extra database call to check whether the ID is valid.

Where possible its best to avoid these extra calls as it can cause load time delays and cost money in production.

2022-12-14 12:00 UTC, lewispricey commented on models/model.js
> +    ($1, $2, $3)
Love the use of parameterization here to avoid SQL injection!

2022-12-14 12:00 UTC, lewispricey commented on error_handling.js
> +    else if (err.code === '23503'){
Great handling of these errors identifying them by the PSQL error code 👍

2022-12-15 10:20 UTC, leekli approved these changes
Thanks for making these changes Lexie, you are free to merge this branch.

2022-12-15 10:23 UTC, merged